// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using delosfera_server.Data;

#nullable disable

namespace delosfera_server.Migrations
{
    [DbContext(typeof(DelosferaDbContext))]
    [Migration("20260727092439_AddUser")]
    partial class AddUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("integer")
                        .HasColumnName("roles_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("RolesId", "UserId")
                        .HasName("pk_user_role");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_role_user_id");

                    b.ToTable("user_role", (string)null);
                });

            modelBuilder.Entity("delosfera_server.Modules.Dictionaries.Models.ApprovalBody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<string>("TitleEn")
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleKg")
                        .HasColumnType("text")
                        .HasColumnName("title_kg");

                    b.Property<string>("TitleRu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ru");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_dictionary_approval_body");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_dictionary_approval_body_parent_id");

                    b.ToTable("dictionary_approval_body", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Asset and Liability Management Committee",
                            TitleKg = "Активдерди жана пассивдерди башкаруу комитети",
                            TitleRu = "Комитет по управлению активами и пассивами",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "General Meeting of Shareholders",
                            TitleKg = "Акционерлердин жалпы жыйыны",
                            TitleRu = "Общее собрание акционеров",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Management Board",
                            TitleKg = "Башкарма",
                            TitleRu = "Правление",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParentId = 3,
                            TitleEn = "Deputy Chairman of the Management Board",
                            TitleKg = "Башкарманын төрагасынын орун басары",
                            TitleRu = "Заместитель Председателя Правления",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParentId = 3,
                            TitleEn = "Chairman of the Management Board",
                            TitleKg = "Башкарманын төрагасы",
                            TitleRu = "Председатель Правления",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParentId = 3,
                            TitleEn = "Member of the Management Board",
                            TitleKg = "Башкарманын мүчөсү",
                            TitleRu = "Член Правления",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Board of Directors",
                            TitleKg = "Директорлор кеңеши",
                            TitleRu = "Совет директоров",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Tariff Committee",
                            TitleKg = "Тарифтик комитет",
                            TitleRu = "Тарифный комитет",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("delosfera_server.Modules.Dictionaries.Models.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<string>("TitleEn")
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleKg")
                        .HasColumnType("text")
                        .HasColumnName("title_kg");

                    b.Property<string>("TitleRu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ru");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_dictionary_keyword");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_dictionary_keyword_parent_id");

                    b.ToTable("dictionary_keyword", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Identification",
                            TitleKg = "Идентификациялоо",
                            TitleRu = "Идентификация",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Analysis",
                            TitleKg = "Анализ",
                            TitleRu = "Анализ",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Reconciliation",
                            TitleKg = "Салыштыруу",
                            TitleRu = "Сверка",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParentId = 3,
                            TitleEn = "Balance Reconciliation",
                            TitleKg = "Калдыктарды салыштыруу",
                            TitleRu = "Сверка остатков",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParentId = 3,
                            TitleEn = "Data Reconciliation",
                            TitleKg = "Маалыматтарды салыштыруу",
                            TitleRu = "Сверка данных",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Responsibility",
                            TitleKg = "Жоопкерчилик",
                            TitleRu = "Ответственность",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Budget",
                            TitleKg = "Бюджет",
                            TitleRu = "Бюджет",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Expense",
                            TitleKg = "Чыгым",
                            TitleRu = "Расход",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParentId = 8,
                            TitleEn = "Material Expense",
                            TitleKg = "Материалдык чыгым",
                            TitleRu = "Расход материальный",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParentId = 8,
                            TitleEn = "Operational Expense",
                            TitleKg = "Операциялык чыгым",
                            TitleRu = "Расход операционный",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Security",
                            TitleKg = "Коопсуздук",
                            TitleRu = "Безопасность",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Matrix",
                            TitleKg = "Матрица",
                            TitleRu = "Матрица",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Plan",
                            TitleKg = "План",
                            TitleRu = "План",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParentId = 13,
                            TitleEn = "Schedule",
                            TitleKg = "План-график",
                            TitleRu = "План-график",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParentId = 13,
                            TitleEn = "Action Plan",
                            TitleKg = "Иш-чаралар планы",
                            TitleRu = "План мероприятий",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Formation",
                            TitleKg = "Түзүү",
                            TitleRu = "Формирование",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Backup Server",
                            TitleKg = "Резервдик сервер",
                            TitleRu = "Резервный сервер",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Automation",
                            TitleKg = "Автоматташтыруу",
                            TitleRu = "Автоматизация",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Continuity",
                            TitleKg = "Үзгүлтүксүздүк",
                            TitleRu = "Непрерывность",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("delosfera_server.Modules.Dictionaries.Models.OrganizationUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<string>("TitleEn")
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleKg")
                        .HasColumnType("text")
                        .HasColumnName("title_kg");

                    b.Property<string>("TitleRu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ru");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_dictionary_organization_unit");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_dictionary_organization_unit_parent_id");

                    b.ToTable("dictionary_organization_unit", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Administrative Affairs Department",
                            TitleKg = "Иштерди башкаруу",
                            TitleRu = "Управление делами",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParentId = 1,
                            TitleEn = "Head of Administrative Affairs Department",
                            TitleKg = "ИБ башчысы",
                            TitleRu = "Начальник УД",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Information Technology Department",
                            TitleKg = "Маалыматтык технологиялар башкармасы",
                            TitleRu = "Управление информационных технологий",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Treasury Operations Department",
                            TitleKg = "Казыналык операциялар башкармасы",
                            TitleRu = "Управление казначейских операций",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Compliance Control Department",
                            TitleKg = "Комплаенс контролдоо башкармасы",
                            TitleRu = "Управление комплаенс контроля",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParentId = 5,
                            TitleEn = "Compliance Control Division",
                            TitleKg = "Комплаенс контролдоо бөлүмү",
                            TitleRu = "Отдел комплаенс контроля",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParentId = 5,
                            TitleEn = "Quality Control Division",
                            TitleKg = "Сапатты контролдоо бөлүмү",
                            TitleRu = "Отдел контроля качества",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Lending Department",
                            TitleKg = "Кредиттөө башкармасы",
                            TitleRu = "Управление кредитования",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Marketing Department",
                            TitleKg = "Маркетинг башкармасы",
                            TitleRu = "Управление маркетинга",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Loan Collateral Department",
                            TitleKg = "Кредиттерди камсыздоо башкармасы",
                            TitleRu = "Управление обеспечения кредитов",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Loan Collateral Department (LCD)",
                            TitleKg = "Кредиттерди камсыздоо башкармасы (ККБ)",
                            TitleRu = "Управление обеспечения кредитов (УОК)",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Payment Services Department",
                            TitleKg = "Төлөм сервистери башкармасы",
                            TitleRu = "Управление платежных сервисов",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParentId = 13,
                            TitleEn = "Claims Handling Division",
                            TitleKg = "Дооматтык иштер бөлүмү",
                            TitleRu = "Отдел претензионной работы",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParentId = 13,
                            TitleEn = "Payment Systems Accounting Division",
                            TitleKg = "Төлөм системаларын эсепке алуу бөлүмү",
                            TitleRu = "Отдел учета платежных систем",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParentId = 13,
                            TitleEn = "Acquiring Division",
                            TitleKg = "Эквайринг бөлүмү",
                            TitleRu = "Отдел эквайринга",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParentId = 13,
                            TitleEn = "Card Issuance Division",
                            TitleKg = "Эмиссия бөлүмү",
                            TitleRu = "Отдел эмиссии",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Customer Relations Department",
                            TitleKg = "Кардарлар менен мамилелер башкармасы",
                            TitleRu = "Управление по взаимоотношениям с клиентами",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Problem Loans Department",
                            TitleKg = "Көйгөйлүү кредиттер менен иштөө башкармасы",
                            TitleRu = "Управление по работе с проблемными кредитами",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Other Property Management Department",
                            TitleKg = "Башка мүлк менен иштөө башкармасы",
                            TitleRu = "Управление по работе с прочей собственностью",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Business Support Department",
                            TitleKg = "Бизнести колдоо башкармасы",
                            TitleRu = "Управление поддержки бизнеса",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Sales Department",
                            TitleKg = "Сатуулар башкармасы",
                            TitleRu = "Управление продаж",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParentId = 22,
                            TitleEn = "Operational Support Division",
                            TitleKg = "Операциялык коштоо бөлүмү",
                            TitleRu = "Отдел операционного сопровождения",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParentId = 22,
                            TitleEn = "Regional Support Division",
                            TitleKg = "Аймактык коштоо бөлүмү",
                            TitleRu = "Отдел регионального сопровождения",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "SME Sales Department",
                            TitleKg = "ЧОБ сатуулар башкармасы",
                            TitleRu = "Управление продаж МСБ",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Risk Management Department",
                            TitleKg = "Тобокелдиктерди башкаруу башкармасы",
                            TitleRu = "Управление рисками",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ParentId = 26,
                            TitleEn = "Operational Risk Sector",
                            TitleKg = "ТБ операциялык тобокелдиктер секторуу",
                            TitleRu = "Сектор операционных рисков УР",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Risk Management Office",
                            TitleKg = "Тобокелдик-менеджмент башкармасы",
                            TitleRu = "Управление риск-менеджмента",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Retail Sales Department",
                            TitleKg = "Чекене сатуулар башкармасы",
                            TitleRu = "Управление розничных продаж",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Retail Products Department",
                            TitleKg = "Чекене продукттар башкармасы",
                            TitleRu = "Управление розничных продуктов",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Strategic Planning and Budgeting Department",
                            TitleKg = "Стратегиялык пландоо жана бюджеттөө башкармасы",
                            TitleRu = "Управление стратегического планирования и бюджетирования",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Human Resources Department",
                            TitleKg = "Адам ресурстарын башкаруу",
                            TitleRu = "Управление человеческими ресурсами",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Methodology and Products Department",
                            TitleKg = "Методология жана продукттар башкармасы",
                            TitleRu = "Управление методологии и продуктов",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Legal Department",
                            TitleKg = "Юридикалык башкарма",
                            TitleRu = "Юридическое управление",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Administrative Division",
                            TitleKg = "Административдик бөлүм",
                            TitleRu = "Административный отдел",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Management Board",
                            TitleKg = "Башкарма",
                            TitleRu = "Правление",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Chancellery",
                            TitleKg = "Канцелярия",
                            TitleRu = "Канцелярия",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Accounting and Reporting Department",
                            TitleKg = "ЭБжО башкармасы",
                            TitleRu = "УБУиО",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Security Department",
                            TitleKg = "Коопсуздук департаменти",
                            TitleRu = "Департамент безопасности",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("delosfera_server.Modules.Dictionaries.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TitleEn")
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleKg")
                        .HasColumnType("text")
                        .HasColumnName("title_kg");

                    b.Property<string>("TitleRu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ru");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_dictionary_position");

                    b.ToTable("dictionary_position", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Chief Specialist",
                            TitleKg = "Башкы адис",
                            TitleRu = "Гл. специалист",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Legal Counsel",
                            TitleKg = "Юрисконсульт",
                            TitleRu = "Юрисконсульт",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Methodologist",
                            TitleKg = "Методолог",
                            TitleRu = "Методолог",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Procurement Specialist",
                            TitleKg = "Сатып алуулар боюнча адис",
                            TitleRu = "Специалист по закупкам",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Deputy Chairman of the Management Board",
                            TitleKg = "Башкарма төрагасынын орун басары",
                            TitleRu = "Зам. Председателя Правления",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Records Clerk",
                            TitleKg = "Иш кагаздарын жүргүзүүчү",
                            TitleRu = "Делопроизводитель",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Head of Department",
                            TitleKg = "Башкарманын башчысы",
                            TitleRu = "Начальник управления",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Head of Division",
                            TitleKg = "Департаменттин башчысы",
                            TitleRu = "Начальник департамента",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "HR Director",
                            TitleKg = "HR-директор",
                            TitleRu = "HR-директор",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Head of Unit",
                            TitleKg = "Бөлүм башчысы",
                            TitleRu = "Начальник отдела",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Chief Accountant",
                            TitleKg = "Башкы бухгалтер",
                            TitleRu = "Главный бухгалтер",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Treasury Director",
                            TitleKg = "Казыналык директору",
                            TitleRu = "Директор казначейства",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Administrator",
                            TitleKg = "Администратор",
                            TitleRu = "Администратор",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("delosfera_server.Modules.Dictionaries.Models.SecurityLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TitleEn")
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleKg")
                        .HasColumnType("text")
                        .HasColumnName("title_kg");

                    b.Property<string>("TitleRu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ru");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_dictionary_security_level");

                    b.ToTable("dictionary_security_level", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Public Access",
                            TitleKg = "Ачык жеткиликтүүлүк",
                            TitleRu = "Открытый доступ",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Confidential",
                            TitleKg = "Конфиденциалдуу",
                            TitleRu = "Конфиденциально",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Secret",
                            TitleKg = "Жашыруун",
                            TitleRu = "Секретно",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Top Secret",
                            TitleKg = "Өтө жашыруун",
                            TitleRu = "Совершенно секретно",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("delosfera_server.Modules.Dictionaries.Models.TypeVnd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TitleEn")
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleKg")
                        .HasColumnType("text")
                        .HasColumnName("title_kg");

                    b.Property<string>("TitleRu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ru");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_dictionary_type_vnd");

                    b.ToTable("dictionary_type_vnd", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Basic Terms of Credit Product",
                            TitleKg = "Кредиттик продукттун негизги шарттары",
                            TitleRu = "Базовые условия кредитного продукта",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Agreement",
                            TitleKg = "Келишим",
                            TitleRu = "Договор",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Job Description",
                            TitleKg = "Кызматтык нускама",
                            TitleRu = "Должностная инструкция",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Instruction",
                            TitleKg = "Нускама",
                            TitleRu = "Инструкция",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Code",
                            TitleKg = "Кодекс",
                            TitleRu = "Кодекс",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Concept",
                            TitleKg = "Концепция",
                            TitleRu = "Концепция",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Limits",
                            TitleKg = "Лимиттер",
                            TitleRu = "Лимиты",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Matrix",
                            TitleKg = "Матрица",
                            TitleRu = "Матрица",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Methodology",
                            TitleKg = "Методика",
                            TitleRu = "Методика",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Plan",
                            TitleKg = "План",
                            TitleRu = "План",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Policy",
                            TitleKg = "Саясат",
                            TitleRu = "Политика",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Regulation",
                            TitleKg = "Жобо",
                            TitleRu = "Положение",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Procedure",
                            TitleKg = "Тартип",
                            TitleRu = "Порядок",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Rules",
                            TitleKg = "Эрежелер",
                            TitleRu = "Правила",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Program",
                            TitleKg = "Программа",
                            TitleRu = "Программа",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Process",
                            TitleKg = "Жараян",
                            TitleRu = "Процедура",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Regulations",
                            TitleKg = "Регламент",
                            TitleRu = "Регламент",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Manual",
                            TitleKg = "Жетекчилик",
                            TitleRu = "Руководство",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "System",
                            TitleKg = "Система",
                            TitleRu = "Система",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleEn = "Charter",
                            TitleKg = "Устав",
                            TitleRu = "Устав",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("delosfera_server.Modules.Users.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<int[]>("PermissionCodes")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("permission_codes");

                    b.Property<string>("TitleEn")
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleKg")
                        .HasColumnType("text")
                        .HasColumnName("title_kg");

                    b.Property<string>("TitleRu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ru");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionCodes = new[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 },
                            TitleEn = "Administrator",
                            TitleKg = "Администратор",
                            TitleRu = "Администратор",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionCodes = new[] { 12, 16 },
                            TitleEn = "Regular User",
                            TitleKg = "Жөнөкөй колдонуучу",
                            TitleRu = "Рядовой пользователь",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionCodes = new[] { 1, 4, 5, 6, 10, 11, 12, 13, 17, 18, 19 },
                            TitleEn = "VND Editor",
                            TitleKg = "ВНД редактору",
                            TitleRu = "Редактор ВНД",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionCodes = new[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 },
                            TitleEn = "Chief VND Editor",
                            TitleKg = "ВНД башкы редактору",
                            TitleRu = "Главный редактор ВНД",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("delosfera_server.Modules.Users.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<int?>("OrgUnitId")
                        .HasColumnType("integer")
                        .HasColumnName("org_unit_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int?>("PositionId")
                        .HasColumnType("integer")
                        .HasColumnName("position_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.HasIndex("OrgUnitId")
                        .HasDatabaseName("ix_user_org_unit_id");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_user_position_id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("delosfera_server.Modules.Users.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_role_roles_id");

                    b.HasOne("delosfera_server.Modules.Users.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_user_user_id");
                });

            modelBuilder.Entity("delosfera_server.Modules.Dictionaries.Models.ApprovalBody", b =>
                {
                    b.HasOne("delosfera_server.Modules.Dictionaries.Models.ApprovalBody", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_dictionary_approval_body_dictionary_approval_body_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("delosfera_server.Modules.Dictionaries.Models.Keyword", b =>
                {
                    b.HasOne("delosfera_server.Modules.Dictionaries.Models.Keyword", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_dictionary_keyword_dictionary_keyword_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("delosfera_server.Modules.Dictionaries.Models.OrganizationUnit", b =>
                {
                    b.HasOne("delosfera_server.Modules.Dictionaries.Models.OrganizationUnit", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_dictionary_organization_unit_dictionary_organization_unit_p");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("delosfera_server.Modules.Users.Models.User", b =>
                {
                    b.HasOne("delosfera_server.Modules.Dictionaries.Models.OrganizationUnit", "OrgUnit")
                        .WithMany()
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_dictionary_organization_unit_org_unit_id");

                    b.HasOne("delosfera_server.Modules.Dictionaries.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_dictionary_position_position_id");

                    b.Navigation("OrgUnit");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("delosfera_server.Modules.Dictionaries.Models.ApprovalBody", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("delosfera_server.Modules.Dictionaries.Models.Keyword", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("delosfera_server.Modules.Dictionaries.Models.OrganizationUnit", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
