using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace delosfera_server.Modules.Dictionaries.Models.Configurations;

public class OrganizationUnitConfiguration : IEntityTypeConfiguration<OrganizationUnit>
{
    public void Configure(EntityTypeBuilder<OrganizationUnit> builder)
    {
        builder.ToTable("dictionary_organization_unit");

        builder.Property(x => x.TitleRu).HasColumnName("title_ru");
        builder.Property(x => x.TitleEn).HasColumnName("title_en");
        builder.Property(x => x.TitleKg).HasColumnName("title_kg");

        builder.HasOne(x => x.HeadUser)
            .WithMany()
            .HasForeignKey(x => x.HeadUserId)
            .OnDelete(DeleteBehavior.Restrict);

        builder.HasOne(x => x.CuratorUser)
            .WithMany()
            .HasForeignKey(x => x.CuratorUserId)
            .OnDelete(DeleteBehavior.Restrict);

        var seedDate = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc);

        // Реальная оргструктура банка, выгруженная с AD/портала (тестовый сервер
        // V3-U2404-DMSTEST1, 06.09.2026) — 149 подразделений, id/external_id/kind
        // взяты 1:1 из "SELECT id, external_id, kind, title_ru FROM
        // dictionary_organization_unit ORDER BY id" на реальном сервере, чтобы
        // локальная база совпадала с продовой по идентификаторам.
        //
        // ParentId взят тем же способом отдельным запросом ("SELECT id, parent_id FROM
        // dictionary_organization_unit ORDER BY id") — подставлен как есть, без пересчёта,
        // так как id локальной и реальной таблицы совпадают 1:1.
        //
        // HeadUserId/CuratorUserId сознательно не заполнены: этих данных с сервера не
        // выгружали (там пользователи вообще другие), это отдельный шаг на будущее.
        //
        // Это ПОЛНАЯ замена временного 11-строчного сида под isrib-пилот
        // (см. историю миграций ReplaceOrgUnitsWithIsribSample) — при переносе тех
        // же 5 пилотных ВНД (7002, 7031, 10067, 10094, 10114) соответствие
        // isrib-названий этим id теперь ищет LocalOrgUnitMapper по live-запросу
        // к этой таблице, а не по старому статическому словарю с id 1-11.
        //
        // 4 названия из старого сида реального аналога не имеют:
        //   - "Совет директоров" — коллегиальный орган, в AD не ведётся, нигде
        //     в демо-сидах не используется, просто выпадает из справочника;
        //   - "Управление продаж малого и среднего бизнеса" — ближайший реальный
        //     аналог "Управление продаж" (id 22);
        //   - "Управление по работе с виртуальными активами" — реального аналога
        //     нет вообще; это и есть тестовый случай для проверки
        //     плейсхолдер+комментарий в LocalOrgUnitMapper (документ 10067);
        //   - "Управление методологии" — ближайший реальный аналог "Отдел
        //     методологии" (id 52, отдел, а не управление).
        builder.HasData(
            new { Id = 1, TitleRu = "Управление делами", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)null, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 2, TitleRu = "Начальник УД", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)1, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Unknown, ExternalId = (int?)null, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 3, TitleRu = "Управление информационных технологий", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)80, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 5, TitleRu = "Управление комплаенс контроля", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)64, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 6, TitleRu = "Отдел комплаенс контроля", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)5, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)null, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 8, TitleRu = "Управление кредитования", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)44, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 10, TitleRu = "Управление маркетинга", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)62, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 11, TitleRu = "Управление обеспечения кредитов", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)null, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 13, TitleRu = "Управление платежных сервисов", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)60, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 14, TitleRu = "Отдел претензионной работы", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)13, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)77, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 16, TitleRu = "Отдел эквайринга", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)13, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)75, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 17, TitleRu = "Отдел эмиссии", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)13, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)74, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 19, TitleRu = "Управление по работе с проблемными кредитами", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)53, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 20, TitleRu = "Управление по работе с прочей собственностью", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)51, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 21, TitleRu = "Управление поддержки бизнеса", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)null, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 22, TitleRu = "Управление продаж", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)null, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 26, TitleRu = "Управление рисками", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)null, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 28, TitleRu = "Управление риск-менеджмента", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)56, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 29, TitleRu = "Управление розничных продаж", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)null, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 30, TitleRu = "Управление розничных продуктов", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)null, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 34, TitleRu = "Юридическое управление", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)39, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 35, TitleRu = "Административный отдел", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)55, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 36, TitleRu = "Правление", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)2, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 37, TitleRu = "Канцелярия", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Unknown, ExternalId = (int?)null, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 38, TitleRu = "УБУиО", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Unknown, ExternalId = (int?)null, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 39, TitleRu = "Департамент безопасности", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)null, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 40, TitleRu = "Отдел устойчивого развития", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Unknown, ExternalId = (int?)null, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 41, TitleRu = "Управление внутреннего аудита", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)38, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 42, TitleRu = "Корпоративный секретарь", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)48, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 43, TitleRu = "Управление бухгалтерского учета и отчетности", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)58, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 44, TitleRu = "Управление планирования и анализа", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)59, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 45, TitleRu = "Управление по работе с залоговым обеспечением", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)57, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 46, TitleRu = "Операционное управление", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)45, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 48, TitleRu = "Управление безопасности", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)52, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 49, TitleRu = "Казначейство", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)40, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 50, TitleRu = "Отдел информационной безопасности", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)42, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 51, TitleRu = "Бэк-офис", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)41, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 52, TitleRu = "Отдел методологии", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)65, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 55, TitleRu = "Отдел кредитного администрирования", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)46, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 56, TitleRu = "Сектор закупок", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)49, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 57, TitleRu = "Сектор делопроизводства", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)35, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)70, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 58, TitleRu = "Секретарь Правления", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Unknown, ExternalId = (int?)null, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 59, TitleRu = "Керемет Банк Головной офис", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)1, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 60, TitleRu = "Контакт-центр", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)10, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)78, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 61, TitleRu = "Отдел кассовых операций", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)145, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)100, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 62, TitleRu = "Отдел отчетности", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)43, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)71, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 63, TitleRu = "Отдел розничного кредитования", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)8, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)68, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 64, TitleRu = "Отдел системного и сетевого сопровождения", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)3, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)81, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 65, TitleRu = "Отдел учета и финансового контроля", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)124, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)29, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 66, TitleRu = "Отдел учета и финансового контроля", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)151, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)102, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 67, TitleRu = "Персонал при Руководстве", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)164, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)79, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 68, TitleRu = "Персонал при руководстве", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)134, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)87, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 69, TitleRu = "Руководство", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)88, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)4, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 70, TitleRu = "Сберегательная касса  № 049-13-41 (Нарын)", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)102, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)12, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 71, TitleRu = "Сектор кредитного сопровождения", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)113, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)21, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 72, TitleRu = "Сектор кредитного сопровождения", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)154, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)111, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 73, TitleRu = "Сектор кредитного сопровождения", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)156, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)120, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 74, TitleRu = "Сектор кредитного сопровождения", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)159, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)128, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 75, TitleRu = "Сектор межбанковских операций", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)51, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)66, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 76, TitleRu = "Кредитный отдел", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)124, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)30, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 77, TitleRu = "Кредитный отдел", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)151, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)103, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 78, TitleRu = "Отдел кредитования и документарных операций", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)8, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)69, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 79, TitleRu = "Отдел технического сопровождения", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)3, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)82, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 80, TitleRu = "Отдел учета АУР", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)43, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)72, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 81, TitleRu = "Отдел учета и финансового контроля", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)113, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)22, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 82, TitleRu = "Отдел учета и финансового контроля", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)156, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)121, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 83, TitleRu = "Отдел учета и финансового контроля", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)159, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)129, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 84, TitleRu = "Персонал при руководстве", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)88, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)5, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 85, TitleRu = "Руководство", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)154, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)112, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 86, TitleRu = "Сектор кредитного сопровождения", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)102, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)13, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 87, TitleRu = "Сектор платежей и расчетов", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)51, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)67, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 88, TitleRu = "Филиал ОАО «Керемет Банк - Чолпон-Ата»", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)3, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 89, TitleRu = "Юридический сектор", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)134, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)88, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 90, TitleRu = "Кредитный отдел", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)113, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)23, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 91, TitleRu = "Кредитный отдел", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)156, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)122, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 92, TitleRu = "Кредитный отдел", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)159, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)130, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 93, TitleRu = "Операционный отдел", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)88, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)6, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 94, TitleRu = "Операционный отдел", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)124, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)31, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 95, TitleRu = "Операционный отдел", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)134, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)89, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 96, TitleRu = "Отдел поддержки и развития АБС", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)3, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)83, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 97, TitleRu = "Отдел учета", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)13, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)76, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 98, TitleRu = "Отдел учета и финансового контроля", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)102, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)14, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 99, TitleRu = "Отдел учета и финансового контроля", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)154, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)113, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 100, TitleRu = "Отдел учета клиентских операций", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)43, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)73, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 101, TitleRu = "Персонал при руководстве", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)151, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)104, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 102, TitleRu = "Филиал ОАО «Керемет Банк - Иссык-Куль»", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)11, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 103, TitleRu = "Кредитный отдел", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)102, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)15, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 104, TitleRu = "Кредитный отдел", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)154, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)114, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 105, TitleRu = "Операционный отдел", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)156, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)123, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 106, TitleRu = "Отдел кассовых операций", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)88, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)7, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 107, TitleRu = "Отдел кассовых операций", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)113, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)24, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 108, TitleRu = "Отдел кассовых операций", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)124, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)32, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 109, TitleRu = "Отдел кассовых операций", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)134, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)90, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 110, TitleRu = "Отдел разработки и интеграции иных программных продуктов", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)3, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)84, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 111, TitleRu = "Руководство", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)159, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)131, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 112, TitleRu = "Сектор кредитного сопровождения", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)151, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)105, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 113, TitleRu = "Филиал ОАО «Керемет Банк - Каракол»", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)20, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 114, TitleRu = "Операционный отдел", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)151, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)106, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 115, TitleRu = "Операционный отдел", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)159, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)132, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 116, TitleRu = "Отдел кассовых операций", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)156, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)124, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 117, TitleRu = "Отдел системного и бизнес анализа", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)3, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)85, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 118, TitleRu = "Отдел учета и финансового контроля", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)88, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)8, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 119, TitleRu = "Персонал при руководстве", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)102, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)16, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 120, TitleRu = "Персонал при руководстве", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)113, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)25, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 121, TitleRu = "Персонал при руководстве", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)154, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)115, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 122, TitleRu = "Руководство", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)124, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)33, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 123, TitleRu = "Сектор кредитного сопровождения", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)134, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)91, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 124, TitleRu = "Филиал ОАО  «Керемет Банк - Кадамжай»", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)28, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 125, TitleRu = "Кредитный отдел", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)88, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)9, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 126, TitleRu = "Кредитный отдел", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)134, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)92, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 127, TitleRu = "Операционный отдел", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)102, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)17, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 128, TitleRu = "Операционный отдел", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)113, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)26, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 129, TitleRu = "Операционный отдел", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)154, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)116, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 130, TitleRu = "Отдел кассовых операций", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)151, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)107, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 131, TitleRu = "Отдел кассовых операций", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)159, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)133, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 132, TitleRu = "Персонал при руководстве", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)124, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)34, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 133, TitleRu = "Руководство", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)156, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)125, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 134, TitleRu = "Филиал ОАО «Керемет Банк - Бишкек»", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)86, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 135, TitleRu = "Отдел кассовых операций", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)102, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)18, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 136, TitleRu = "Отдел кассовых операций", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)154, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)117, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 137, TitleRu = "Отдел корреспондентских отношений", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)43, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 138, TitleRu = "Отдел учета и финансового контроля", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)134, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)93, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 139, TitleRu = "Персонал при руководстве", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)156, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)126, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 140, TitleRu = "Персонал при руководстве", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)159, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)134, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 141, TitleRu = "Руководство", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)113, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)27, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 142, TitleRu = "Руководство", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)151, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)108, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 143, TitleRu = "Сектор кредитного сопровождения", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)88, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)10, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 144, TitleRu = "Сектор кредитного сопровождения", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)124, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)35, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 145, TitleRu = "Филиал ОАО  «Керемет Банк -Чуй»", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)99, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 146, TitleRu = "Руководство", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)102, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)19, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 147, TitleRu = "Руководство", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)134, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)94, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 148, TitleRu = "Сберегательная касса № 049-20-46 (Баткен)", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)124, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)36, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 149, TitleRu = "Сберегательная касса № 049-25-36 (Таш-Кумыр)", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)154, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)118, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 150, TitleRu = "Сберегательная касса № 049-32-34 (Узген)", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)151, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)109, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 151, TitleRu = "Филиал ОАО  «Керемет Банк - Ош»", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)101, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 152, TitleRu = "Сберегательная касса № 049-20-18 (Кызыл-Кия)", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)124, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)37, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 153, TitleRu = "Сектор по обслуживанию юридических лиц", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)134, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)95, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 154, TitleRu = "Филиал ОАО «Керемет Банк - Жалалабат»", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)110, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 155, TitleRu = "Сектор по обслуживанию физических лиц", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)134, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)96, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 156, TitleRu = "Филиал ОАО «Керемет Банк - Кара-Балта»", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)119, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 157, TitleRu = "Отдел систем денежных перевод", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)47, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 158, TitleRu = "Сберегательная касса № 049-01-45 (Манас)", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)134, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)97, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 159, TitleRu = "Филиал ОАО «Керемет Банк - Талас»", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)127, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 160, TitleRu = "Сберегательная касса № 049-01-10 (Токмок)", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)134, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)98, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 161, TitleRu = "Отдел Антифрод", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)50, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 162, TitleRu = "Управление  человеческими ресурсами", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Division, ExternalId = (int?)54, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 163, TitleRu = "Отдел дистанционного банковского обслуживания", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)61, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 164, TitleRu = "Руководство", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)59, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Department, ExternalId = (int?)63, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate },
            new { Id = 165, TitleRu = "Прогон ролей", TitleEn = (string?)null, TitleKg = (string?)null, ParentId = (int?)null, HeadUserId = (int?)null, CuratorUserId = (int?)null, Kind = OrgUnitKind.Unknown, ExternalId = (int?)null, RequiresPaperSz = false, CreatedAt = seedDate, UpdatedAt = seedDate }
        );
    }
}
